# Generated by Django 5.1.4 on 2024-12-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
