# Generated by Django 5.1.4 on 2024-12-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='test',
            field=models.IntegerField(null=True),
        ),
    ]
