# Generated by Django 5.1.4 on 2024-12-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id',
            new_name='ids',
        ),
    ]
