# Generated by Django 5.1.4 on 2024-12-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_id_cart_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='ids',
            new_name='id',
        ),
    ]
