# Generated by Django 5.1.4 on 2025-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
