# Generated by Django 5.1.4 on 2025-04-21 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login_time',
        ),
    ]
